[CREATED] Create reservation
JBunCE/microservice-reservation pull request #1
Opened 2023-03-19 00:19 UTC by JoseABermudez57

2023-03-20 05:47 UTC, JBunCE requested changes

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/controllers/ReservationController.java
> +}
Toda esta parte la haremos integrando RabbitMQ

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/controllers/ReservationController.java
> +}
arreglar en la siguiente tarea

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/controllers/dtos/requests/CreateReservationRequest.java
> +    private Slot slot;
Un DAO (Data Access Object) no se puede mandar en un DTO esta prohibidisima esa mdr ademas que lo que necesitamos es solo el ID secundario de esa tabla que es el numero del estacionamiento es decir solamente un dato 
`
```java
// podria ser
private String slotNumber;
```

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/controllers/dtos/responses/BaseResponse.java
> +    private HttpStatus httpStatus;
Aqui agrega otro campo 

```java
private Integer statusCode
```

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/controllers/dtos/requests/CreateReservationRequest.java
> +    private LocalTime hour;
Ese chavo, no puedes mandar un LocalDate o un LocalTime por un DTO, Lo mandas en string y lo conviertes 
Crea una utileria para esa mdr

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/controllers/dtos/responses/CreateReservationResponse.java
> +public record CreateReservationResponse (Boolean current) {}
El response solo regresa true o false? como sabes que si se creo bien tu entidad? o como sabe el front que la entidad se creo con todos los campos si el no puede acceder a la base de datos?

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/controllers/dtos/responses/GetSlotResponse.java
> +public record GetSlotResponse(Integer place) {}
No necesitas un response del slot en todo caso si lo necesitraras porque regresa un Integer place? y si mi estacionamiento es el B-16 o el A-18 el que solo regrese un numero es muy ambiguo

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/entities/Reservation.java
> +    private String user;
La variable donde almacenare la llave foranea del usuario que va a recervar deberia ser Long no String y deberia ir hasta abajo

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/entities/Slot.java
> +    private Character section;
bien podrian ir los dos en un String

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/entities/Slot.java
> +    private Boolean available;
Aqui igual solo necesitas una variable que diga si esta reservado o si esta disponible
```java
private Boolean isAvaliable;
// true = disponible | false = ocupado
```

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/entities/Slot.java
> +    private List<Reservation> reservations;
No necesitamos la relacion de este lado de la entidad puedes dejar solamente la de Reservation

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/entities/Reservation.java
> +    private LocalTime hour;
Aqui puedes juntar estas dos con un 
```java
private LocalDateTime time;
``` 
y validar que solamente haya una reservacion en una hora y una fecha con

```java
@Column(unique = true)
private LocalDateTime schedule
```

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/repositories/IReservationRepository.java
> +    Optional<Reservation> findByDateAndHourAndSlot(LocalDate data, LocalTime hour, Slot slot);
je creo que con lo de la entidad esto ya no seria necesario

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/services/ReservationServiceImpl.java
> +    ISlotRepository slotRepository;
No
Una clase Servicio solo puede tener un repositorio y es el suyo y no puede tener el de alguien mas borra esto y si necesitas acceder a datos de Slot usa su servicio porque un servicio si puede comunicarse con otro servicio

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/services/ReservationServiceImpl.java
> +        Slot slot = slotRepository.findById(request.getSlot().getId()).orElseThrow(NotFoundException::new);
Esta logica deberia ir en el servicio de slot

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/services/ReservationServiceImpl.java
> +        if (validate.isEmpty()){
esto se valida con @Column(unique = true) 🤓

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/services/ReservationServiceImpl.java
> +            reservationRepository.save(reservation);
Todo esto tendras que cambiarlos por los cambios que te pedi arriba

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/services/ReservationServiceImpl.java
> +    }
esto no regresa ningun response en data

2023-03-20 05:47 UTC, JBunCE commented on proyectinicializado/bpra/src/main/resources/application.properties
> +server.address=0.0.0.0
quita esto

2023-03-20 05:47 UTC, JBunCE commented
UwU toca reparar todo eso

2023-03-20 06:32 UTC, JoseABermudez57 commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/entities/Slot.java
> +    private Boolean available;
"reserved" está pensado para aquellos lugares que están reservados para discapacitados, "available" si es para verificar si está disponible o no, pero tomaré el consejo del nombre

2023-03-20 15:30 UTC, JoseABermudez57 commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/entities/Reservation.java
> +    private LocalTime hour;
It can't be Unique because two Reservations can be made at the same time and date but in different Slots

2023-03-20 20:50 UTC, JBunCE requested changes

2023-03-20 20:50 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/entities/Reservation.java
> +    private LocalDateTime isoDateTime;
le puedes oner de nombre al atributo schedule para ya no tener que que poner el name en @Column

2023-03-20 20:50 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/entities/Reservation.java
> +    private BigDecimal price;
Porque BigDecimal?

2023-03-20 20:50 UTC, JBunCE commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/services/ReservationServiceImpl.java
> +    }
No ncesitas este metodo para llamar a otro metodo no necesitas una bolsa para guardar bolsas

2023-03-20 20:51 UTC, JBunCE commented
ya lo ultimo tilin

2023-03-20 21:05 UTC, JoseABermudez57 commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/entities/Reservation.java
> +    private LocalDateTime isoDateTime;
Sí, pero para que en el código se tenga referencia de que es en formato ISO

2023-03-20 21:05 UTC, JoseABermudez57 commented on proyectinicializado/bpra/src/main/java/com/bpra/bpra/entities/Reservation.java
> +    private BigDecimal price;
Porqué es recomendable para los precios.
P. D. hay un tipo que pagó un dineral en un estacionamiento, mejor prevenir que lamentar (si queda de más, reacciona)

2023-03-22 00:55 UTC, JBunCE requested changes
Creo que se puede arreglar mejor y los nombres se pueden simplificar por ejemplo a la hora y fecha podrias ponerle Schedule pero simon por ahora para que sigas trabajando con lo demas yo creo que asi queda

2023-03-22 00:58 UTC, merged